// src/borders.js

export const borders = {
    "Afghanistan": ["Iran", "Pakistan", "Tajikistan", "Turkmenistan", "Uzbekistan", "China"],
    "Albania": ["Greece", "Kosovo", "North Macedonia", "Montenegro"],
    "Algeria": ["Libya", "Mali", "Mauritania", "Morocco", "Niger", "Tunisia", "Western Sahara"],
    "Angola": ["Dem. Rep. Congo", "Congo", "Namibia", "Zambia"],
    "Argentina": ["Bolivia", "Brazil", "Chile", "Paraguay", "Uruguay"],
    "Armenia": ["Azerbaijan", "Georgia", "Iran", "Turkey"],
    "Austria": ["Czechia", "Germany", "Hungary", "Italy", "Liechtenstein", "Slovakia", "Slovenia", "Switzerland"],
    "Azerbaijan": ["Armenia", "Georgia", "Iran", "Russia", "Turkey"],
    "Australia": [],
    "Bangladesh": ["India", "Myanmar"],
    "Belarus": ["Latvia", "Lithuania", "Poland", "Russia", "Ukraine"],
    "Belgium": ["France", "Germany", "Luxembourg", "Netherlands"],
    "Belize": ["Guatemala", "Mexico"],
    "Benin": ["Burkina Faso", "Niger", "Nigeria", "Togo"],
    "Bhutan": ["China", "India"],
    "Bolivia": ["Argentina", "Brazil", "Chile", "Paraguay", "Peru"],
    "Bosnia and Herz.": ["Croatia", "Montenegro", "Serbia"],
    "Botswana": ["Namibia", "South Africa", "Zambia", "Zimbabwe"],
    "Brazil": ["Argentina", "Bolivia", "Colombia", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela", "French Guiana"],
    "Brunei": ["Malaysia"],
    "Bulgaria": ["Greece", "North Macedonia", "Romania", "Serbia", "Turkey"],
    "Burkina Faso": ["Benin", "Côte d'Ivoire", "Ghana", "Mali", "Niger", "Togo"],
    "Burundi": ["Dem. Rep. Congo", "Rwanda", "Tanzania"],
    "Cambodia": ["Laos", "Thailand", "Vietnam"],
    "Cameroon": ["Central African Rep.", "Chad", "Eq. Guinea", "Gabon", "Nigeria", "Congo"],
    "Canada": ["United States of America"],
    "Central African Rep.": ["Cameroon", "Chad", "Dem. Rep. Congo", "Congo", "South Sudan", "Sudan"],
    "Chad": ["Cameroon", "Central African Rep.", "Libya", "Niger", "Nigeria", "Sudan"],
    "Chile": ["Argentina", "Bolivia", "Peru"],
    "China": ["Afghanistan", "Bhutan", "India", "Kazakhstan", "North Korea", "Kyrgyzstan", "Laos", "Mongolia", "Myanmar", "Nepal", "Pakistan", "Russia", "Tajikistan", "Vietnam"],
    "Colombia": ["Brazil", "Ecuador", "Panama", "Peru", "Venezuela"],
    "Congo": ["Angola", "Cameroon", "Central African Rep.", "Dem. Rep. Congo", "Gabon"],
    "Costa Rica": ["Nicaragua", "Panama"],
    "Côte d'Ivoire": ["Burkina Faso", "Ghana", "Guinea", "Liberia", "Mali"],
    "Croatia": ["Bosnia and Herz.", "Hungary", "Montenegro", "Serbia", "Slovenia"],
    "Czechia": ["Austria", "Germany", "Poland", "Slovakia"],
    "Dem. Rep. Congo": ["Angola", "Burundi", "Central African Rep.", "Congo", "Rwanda", "South Sudan", "Tanzania", "Uganda", "Zambia"],
    "Denmark": ["Germany"],
    "Djibouti": ["Eritrea", "Ethiopia", "Somalia"],
    "Dominican Rep.": ["Haiti"],
    "Ecuador": ["Colombia", "Peru"],
    "Egypt": ["Israel", "Libya", "Sudan"],
    "El Salvador": ["Guatemala", "Honduras"],
    "Eq. Guinea": ["Cameroon", "Gabon"],
    "Eritrea": ["Djibouti", "Ethiopia", "Sudan"],
    "Estonia": ["Latvia", "Russia"],
    "eSwatini": ["Mozambique", "South Africa"],
    "Ethiopia": ["Djibouti", "Eritrea", "Kenya", "Somalia", "South Sudan", "Sudan"],
    "Finland": ["Norway", "Russia", "Sweden"],
    "France": ["Andorra", "Belgium", "Germany", "Italy", "Luxembourg", "Spain", "Switzerland"],
    "French Guiana": ["Brazil", "Suriname"],
    "Gabon": ["Cameroon", "Congo", "Eq. Guinea"],
    "Gambia": ["Senegal"],
    "Georgia": ["Armenia", "Azerbaijan", "Russia", "Turkey"],
    "Germany": ["Austria", "Belgium", "Czechia", "Denmark", "France", "Luxembourg", "Netherlands", "Poland", "Switzerland"],
    "Ghana": ["Burkina Faso", "Côte d'Ivoire", "Togo"],
    "Greece": ["Albania", "Bulgaria", "North Macedonia", "Turkey"],
    "Greenland": [],
    "Guatemala": ["Belize", "El Salvador", "Honduras", "Mexico"],
    "Guinea": ["Côte d'Ivoire", "Guinea-Bissau", "Liberia", "Mali", "Senegal", "Sierra Leone"],
    "Guinea-Bissau": ["Guinea", "Senegal"],
    "Guyana": ["Brazil", "Suriname", "Venezuela"],
    "Haiti": ["Dominican Rep."],
    "Honduras": ["El Salvador", "Guatemala", "Nicaragua"],
    "Hungary": ["Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Ukraine"],
    "Iceland": [],
    "India": ["Bangladesh", "Bhutan", "China", "Myanmar", "Nepal", "Pakistan"],
    "Indonesia": ["Malaysia", "Papua New Guinea", "Timor-Leste"],
    "Iran": ["Afghanistan", "Armenia", "Azerbaijan", "Iraq", "Pakistan", "Turkey", "Turkmenistan"],
    "Iraq": ["Iran", "Jordan", "Kuwait", "Saudi Arabia", "Syria", "Turkey"],
    "Ireland": ["United Kingdom"],
    "Israel": ["Egypt", "Jordan", "Lebanon", "Palestine", "Syria"],
    "Italy": ["Austria", "France", "Slovenia", "Switzerland"],
    "Jamaica": [],
    "Japan": [],
    "Jordan": ["Iraq", "Israel", "Palestine", "Saudi Arabia", "Syria"],
    "Kazakhstan": ["China", "Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
    "Kenya": ["Ethiopia", "Somalia", "South Sudan", "Tanzania", "Uganda"],
    "Kosovo": ["Albania", "Montenegro", "North Macedonia", "Serbia"],
    "Kuwait": ["Iraq", "Saudi Arabia"],
    "Kyrgyzstan": ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
    "Laos": ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
    "Latvia": ["Belarus", "Estonia", "Lithuania", "Russia"],
    "Lebanon": ["Israel", "Syria"],
    "Lesotho": ["South Africa"],
    "Liberia": ["Côte d'Ivoire", "Guinea", "Sierra Leone"],
    "Libya": ["Algeria", "Chad", "Egypt", "Niger", "Sudan", "Tunisia"],
    "Lithuania": ["Belarus", "Latvia", "Poland", "Russia"],
    "Luxembourg": ["Belgium", "France", "Germany"],
    "Madagascar": [],
    "Malawi": ["Mozambique", "Tanzania", "Zambia"],
    "Malaysia": ["Brunei", "Indonesia", "Thailand"],
    "Mali": ["Algeria", "Burkina Faso", "Guinea", "Mauritania", "Niger", "Senegal"],
    "Mauritania": ["Algeria", "Mali", "Senegal", "Western Sahara"],
    "Mexico": ["Belize", "Guatemala", "United States of America"],
    "Moldova": ["Romania", "Ukraine"],
    "Mongolia": ["China", "Russia"],
    "Montenegro": ["Albania", "Bosnia and Herz.", "Croatia", "Kosovo", "Serbia"],
    "Morocco": ["Algeria", "Western Sahara"],
    "Mozambique": ["eSwatini", "Malawi", "South Africa", "Tanzania", "Zambia", "Zimbabwe"],
    "Myanmar": ["Bangladesh", "China", "India", "Laos", "Thailand"],
    "Namibia": ["Angola", "Botswana", "South Africa", "Zambia"],
    "Nepal": ["China", "India"],
    "Netherlands": ["Belgium", "Germany"],
    "New Zealand": [],
    "Nicaragua": ["Costa Rica", "Honduras"],
    "Niger": ["Algeria", "Benin", "Burkina Faso", "Chad", "Libya", "Mali", "Nigeria"],
    "Nigeria": ["Benin", "Cameroon", "Chad", "Niger"],
    "North Korea": ["China", "Russia", "South Korea"],
    "North Macedonia": ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
    "Norway": ["Finland", "Russia", "Sweden"],
    "Oman": ["Saudi Arabia", "United Arab Emirates", "Yemen"],
    "Pakistan": ["Afghanistan", "China", "India", "Iran"],
    "Palestine": ["Israel", "Jordan"],
    "Panama": ["Colombia", "Costa Rica"],
    "Papua New Guinea": ["Indonesia"],
    "Paraguay": ["Argentina", "Bolivia", "Brazil"],
    "Peru": ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador"],
    "Philippines": [],
    "Poland": ["Belarus", "Czechia", "Germany", "Lithuania", "Russia", "Slovakia", "Ukraine"],
    "Portugal": ["Spain"],
    "Qatar": ["Saudi Arabia"],
    "Romania": ["Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
    "Russia": ["Azerbaijan", "Belarus", "China", "Estonia", "Finland", "Georgia", "Kazakhstan", "Latvia", "Lithuania", "Mongolia", "North Korea", "Norway", "Poland", "Ukraine"],
    "Rwanda": ["Burundi", "Dem. Rep. Congo", "Tanzania", "Uganda"],
    "Saudi Arabia": ["Iraq", "Jordan", "Kuwait", "Oman", "Qatar", "United Arab Emirates", "Yemen"],
    "Senegal": ["Gambia", "Guinea", "Guinea-Bissau", "Mali", "Mauritania"],
    "Serbia": ["Bosnia and Herz.", "Bulgaria", "Croatia", "Hungary", "Kosovo", "Montenegro", "North Macedonia", "Romania"],
    "Sierra Leone": ["Guinea", "Liberia"],
    "Slovakia": ["Austria", "Czechia", "Hungary", "Poland", "Ukraine"],
    "Slovenia": ["Austria", "Croatia", "Hungary", "Italy"],
    "Somalia": ["Djibouti", "Ethiopia", "Kenya"],
    "South Africa": ["Botswana", "eSwatini", "Lesotho", "Mozambique", "Namibia", "Zimbabwe"],
    "South Korea": ["North Korea"],
    "South Sudan": ["Central African Rep.", "Dem. Rep. Congo", "Ethiopia", "Kenya", "Sudan", "Uganda"],
    "Spain": ["France", "Portugal"],
    "Sri Lanka": [],
    "Sudan": ["Central African Rep.", "Chad", "Egypt", "Eritrea", "Ethiopia", "Libya", "South Sudan"],
    "Suriname": ["Brazil", "Guyana", "French Guiana"],
    "Sweden": ["Finland", "Norway"],
    "Switzerland": ["Austria", "France", "Germany", "Italy", "Liechtenstein"],
    "Syria": ["Iraq", "Israel", "Jordan", "Lebanon", "Turkey"],
    "Taiwan": [],
    "Tajikistan": ["Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"],
    "Tanzania": ["Burundi", "Dem. Rep. Congo", "Kenya", "Malawi", "Mozambique", "Rwanda", "Uganda", "Zambia"],
    "Thailand": ["Cambodia", "Laos", "Malaysia", "Myanmar"],
    "Timor-Leste": ["Indonesia"],
    "Togo": ["Benin", "Burkina Faso", "Ghana"],
    "Tunisia": ["Algeria", "Libya"],
    "Turkey": ["Armenia", "Azerbaijan", "Bulgaria", "Georgia", "Greece", "Iran", "Iraq", "Syria"],
    "Turkmenistan": ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan"],
    "Uganda": ["Dem. Rep. Congo", "Kenya", "Rwanda", "South Sudan", "Tanzania"],
    "Ukraine": ["Belarus", "Hungary", "Moldova", "Poland", "Romania", "Russia", "Slovakia"],
    "United Arab Emirates": ["Oman", "Saudi Arabia"],
    "United Kingdom": ["Ireland"],
    "United States of America": ["Canada", "Mexico"],
    "Uruguay": ["Argentina", "Brazil"],
    "Uzbekistan": ["Afghanistan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan"],
    "Venezuela": ["Brazil", "Colombia", "Guyana"],
    "Vietnam": ["Cambodia", "China", "Laos"],
    "Western Sahara": ["Algeria", "Mauritania", "Morocco"],
    "Yemen": ["Oman", "Saudi Arabia"],
    "Zambia": ["Angola", "Botswana", "Dem. Rep. Congo", "Malawi", "Mozambique", "Namibia", "Tanzania", "Zimbabwe"],
    "Zimbabwe": ["Botswana", "Mozambique", "South Africa", "Zambia"]
};